### ISSUE TITLE
如果Leader绑定VIP后，挂掉了，请问已绑定的VIP会自动释放么?

### ISSUE THREAD

**Issue by bingoohuang** [zdyxry/sparrow#2]
如题

**Comment by zdyxry** [comment]
@bingoohuang  
如果程序异常退出，目前监控了 os.Interrupt 信号则会主动清除 VIP 配置；
如果节点异常掉电/关机/网络失联，那么 VIP 自身也无法连接，我理解无需做相关处理，其他节点自动配置新的 VIP 即可。
